---

- name: Install nginx_extra_packages
  ansible.builtin.openbsd_pkg:
    name: "{{ nginx_extra_packages }}"
    state: present

- name: Install nginx
  ansible.builtin.openbsd_pkg:
    name: "{{ nginx_package }}"
    state: present

- name: Install nginx_passlib_package
  ansible.builtin.openbsd_pkg:
    name: "{{ nginx_passlib_package }}"
    state: present
