---

- name: Install nginx_extra_packages
  openbsd_pkg:
    name: "{{ nginx_extra_packages }}"
    state: present

- name: Install nginx
  openbsd_pkg:
    name: "{{ nginx_package }}"
    state: present

- name: Install nginx_passlib_package
  openbsd_pkg:
    name: "{{ nginx_passlib_package }}"
    state: present
