---

- name: Install nginx_extra_packages
  ansible.builtin.pkgng:
    name: "{{ nginx_extra_packages }}"
    state: present

- name: Install nginx
  ansible.builtin.pkgng:
    name: "{{ nginx_package }}"
    state: present

- name: Install nginx_passlib_package
  ansible.builtin.pkgng:
    name: "{{ nginx_passlib_package }}"
    state: present

- name: Enable nginx_service
  ansible.builtin.service:
    name: "{{ nginx_service }}"
    enabled: yes
