---

# XXX this task should have been in `tasks/main.yml` but ansible older than 2.2
# does not understand `include_role` and bails out.
- name: Include x509_certificate
  include_role:
    name: trombik.x509_certificate
